### ISSUE TITLE
Remove border radius on top menu

### ISSUE THREAD

**Issue by ineffyble** [ineffyble/pleasepet#23]
> This is delightful. Please consider removing the border-radii from the menu bar so it's square to the top of the screen. Otherwise keep up the good work.

**Comment by manavo** [comment]
Here's the CSS rule you need if it helps:

```css
.navbar.navbar-inverse {
	-moz-border-radius: 0;
	-webkit-border-radius: 0;
	border-radius: 0;
}
```
